# Generated by Django 3.0.8 on 2020-07-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decider', '0004_auto_20200713_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='code',
            field=models.SlugField(default='house-cleanup', max_length=64),
            preserve_default=False,
        ),
    ]
